name: VIB and Sign
on:
  push: 
    branches:
       - main
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com
jobs:
  doit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    
      id-token: write # This enables OIDC
    steps:
      - name: Info           
        run: |
          ls -la $HOME
          echo "Searching docker..."
          which docker

      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        
      - name: Sign the package
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          docker login ghcr.io -u mpermar@gmail.com -p ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          cosign sign ghcr.io/mpermar-tests/wordpress:13.1.11
